@startwbs

skinparam defaultFontName Helvetica
skinparam DefaultTextAlignment right

* ...

**[#SkyBlue] كلاب

***[#pink] قصي

**** عبد مناف

***** هاشم
****** عبد المطّلب

******* عبد الله
******** محمْد

******* عباس
******** عبد الله

***** عبد شمس
****** أمية
******* أبو العاص

******** الحكم
********* مروان
********** عبد العزيز
*********** عمر

******** عفان
********* عثمان

**** عبد العزى
***** أسد
****** خُوَيلد
******* العوّام
******** الزبير
********* عروة

*** زهرة
**** الحارث
***** عبد الله
****** شهاب
******* عبد الله
******** عبيد الله
********* مسلم
********** محمد

** ثقيف
*** عوف
**** سعد
***** عمرو
****** كعب
******* مالك
******** معتب
********* مسعود
********** أبو عامر
*********** شعبة
************ المغيرة

** الخزرج
*** الحارث
**** عوف
***** خُدارة
****** عطية
******* عسيرة
******** أسيرة
********* ثعلبة
********** عمرو
*********** عقبة

@endwbs
