@startwbs

skinparam defaultFontName Courier
skinparam DefaultTextAlignment right

* ...

**[#SkyBlue] كلاب
***[#pink] قصي
**** عبد العزى
***** أسد
****** خُوَيلد
******* العوّام
******** الزبير
********* عروة

**** عبد مناف
***** هشام
****** عبد المطّلب
******* عبد الله
******** محمْد

***** عبد شمس
****** أمية
******* أبي العاص
******** الحكم
********* مروان
********** عبد العزيز
*********** عمر

*** زهرة
**** الحارث
***** عبد الله
****** شهاب
******* عبد الله
******** عبيد الله
********* مسلم
********** محمد

** ثقيف
*** عوف
**** سعد
***** عمرو
****** كعب
******* مالك
******** معتب
********* مسعود
********** أبي عامر
*********** شعبة
************ المغيرة

** الخزرج
*** الحارث
**** عوف
***** خُدارة
****** عطية
******* عسيرة
******** أسيرة
********* ثعلبة
********** عمرو
*********** عقبة

@endwbs
