@startwbs

skinparam DefaultFontName Helvetica
skinparam DefaultFontSize 16
skinparam DefaultTextAlignment right

* ...

**[#SkyBlue] كلاب

***[#white] قصي

**** عبد مناف

***** هاشم
****** عبد المطّلب

******* عبد الله
******** محمْد

*******[#LightGreen] عباس
********[#LightGreen] عبد الله

***** عبد شمس
****** أمية
******* أبو العاص

******** الحكم
********* مروان
********** عبد العزيز
***********[#pink] عمر

******** عفّان
*********[#LightGreen] عثمان

**** عبد العزى
***** أسد
****** خُوَيلد
******* العوّام
********[#LightGreen] الزبير
*********[#pink] عروة

*** زهرة
**** الحارث
***** عبد الله
****** شهاب
******* عبد الله
******** عبيد الله
********* مسلم
**********[#pink] محمد

** ثقيف
*** عوف
**** سعد
***** عمرو
****** كعب
******* مالك
******** معتب
********* مسعود
********** أبو عامر
*********** شعبة
************[#LightGreen] المغيرة

** الخزرج

*** الحارث
**** عوف
***** خُدارة
****** عطية
******* عسيرة
******** أسيرة
********* ثعلبة
********** عمرو
***********[#LightGreen] عقبة

*** عمرو
**** ثعلبة
***** النجار
****** مازن
******* ...
********[#LightGreen] أبو حسن

*********[#LightGreen] عُمارة
**********[#pink] يحيى
***********[#pink] عمرو

*********[#LightGreen] عمرو

@endwbs
