= عثمان بن عفان

[%header, cols=">s,>5"]
|===
2+^s|عثمان بن عفان

|الكنية
|

|الاسم
|عثمان بن عفان بن أبي العاص بن أمية بن عبد شمس

|النسبة
|القرشي الأموي

|اللفب
|ذو النورين

|الطبقة
|صحابي

|الميلاد
|ولد بعد الفيل بست سنين

|الوفاء
|استشهد في ذي الحجة سنة ٣٥

|من روى عنه
|

|ما روى
|

|ترجمة
a|
ثالث الخلفاء الراشدين +
أحد العشرة المبشَّرة +
من السابقين الأولين +
هاجر الهجرتين +
وزوَّجه النبي رقيَّة، فلما توفيت أيام بدر زوَّجه أختها أم كلثوم فلُقّب بذي النورين +

وروى الترمذي وأحمد والحاكم، بسند حسن، عن عبد الرحمن بن سمُرة قال: جاء عثمان إلى النبي بألف دينار في ثوبه، حين جهَّز جيش العُسرة footnote:[سنة تسع من الهجرة]، فصبها في حجر النبي، فجعل يقلبها بيده ويقول: "ما ضرَّ عثمان ما عمل بعد اليوم" +
وروى الطبراني في المعجم الكبير: "لما قدم المهاجرون المدينة استنكروا الماء، وكانت لرجل footnote:[وقال ابن بطال: كانت ليهودي] من بني غفار عين يقال لها رومة footnote:[وبئر رومة من آبار المدينة في آخر حرَّة المدينة الغربيَّة - حرة الوَبَرة - إذا أكْنَعتَ في مجمع الأسيال]، وكان يبيع منها القِرْبة بمُدّ footnote:[أي بمد من التمر]، فقال رسول الله : "بِعنيها بعَين في الجنة"، فقال: ليس لي ولا لِعيالي غيرها، لا أستطيع ذلك. فبلغ ذلك عثمان فاشتراها بخمسة وثلاثين ألف درهم، ثم أتى النبي فقال: أتجعل لي مثل الذي جعلته له، عيناً في الجنة إن اشتريتها؟ قال: "نعم". قال: قد اشتريتها وجعلتها للمسلمين" footnote:[وأصل القصة في الصحيح] +

تولى الخلافة في محرَّم سنة ٢٤ +
|===
