@startwbs

*[#SkyBlue] كلاب
**[#pink] قصي
*** عبد العزى
**** أسد
***** خُوَيلد
****** العوّام
******* الزبير
******** عروة
*** عبد مناف
**** هشام
***** عبد المطّلب
****** عبد الله
******* محمْد

@endwbs
