@startwbs

skinparam DefaultFontName Helvetica
skinparam DefaultFontSize 24
skinparam DefaultTextAlignment right

+ المائع

 + الماء

  + المُطْلَق

   +[#LightGreen] الذي لا يزال على حالته الأصلية

    +_ ماء المطر
    -_ ماء الأنهار
    +_ ماء البحار
    -_ ماء العيون
    +_ ماء الآبار

   -[#LightGreen] الذي تغيَّر بمخالطة شيء طاهر ملازم له غالباً

    +_ التراب
    -_ أوراق الأشجار
    +_ الكِبريت
    -_ ...

   +[#SkyBlue] الذي اختلط بطاهر

   - الذي اختلط بنجاسة

    +[#pink] إذا تغير أحد أوصافه

    - إذا لم يتغير أحد أوصافه

     +[#white] إذا قلّ

     -[#SkyBlue] إذا كثُر

  -[#SkyBlue] المُقَيَّد

   +_ ماء الورد

 +[#SkyBlue] المائع الطاهر سوى الماء

  +_ اللبن
  -_ الخلّ
  +_ ...

legend right
    |<#LightGreen> طَهور بالاتفاق |
    |<#SkyBlue> طاهر غير مطهّر بالاتفاق |
    |<#pink> نجس بالاتفاق |
    |<#white> مختلاف فيه |
endlegend

@endwbs
